FROM apache/airflow:2.7.0

USER root
RUN apt-get update && apt-get install -y default-jdk-headless procps && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /app && ln -s /opt/airflow/data /app/data
ENV JAVA_HOME=/usr/lib/jvm/default-java

USER airflow
RUN pip install --no-cache-dir pyspark==3.5.0 pyarrow