FROM python:3.10-slim

RUN apt-get update && apt-get install -y default-jdk-headless && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/default-java

WORKDIR /app

RUN pip install --no-cache-dir pyspark==3.5.0

CMD ["tail", "-f", "/dev/null"]